import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface PlayerData {
  rank: number;
  name: string;
  points: number;
  avatarUrl?: string;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { players, language } = await req.json();
    
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    // Build the player list for the prompt
    const playerList = (players as PlayerData[])
      .slice(0, 10)
      .map((p, i) => {
        const medal = i === 0 ? "🥇" : i === 1 ? "🥈" : i === 2 ? "🥉" : `${i + 1}.`;
        return `${medal} ${p.name} - ${p.points} pts`;
      })
      .join("\n");

    const brandName = language === "zh" ? "羽球人联赛" : "Badminton League";
    const subtitle = language === "zh" ? "2026 官方积分榜" : "2026 Official Rankings";
    const today = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });

    const prompt = `Create a professional, eye-catching sports ranking poster for a badminton league with these specifications:

DESIGN STYLE:
- Modern sports broadcast aesthetic (like ESPN, BWF World Rankings)
- Premium feel with dynamic visual effects
- Deep red/maroon gradient background (#8B0000 to #4A0000) with subtle geometric patterns
- Dramatic lighting effects and lens flares
- Badminton shuttlecock graphics as decorative elements

LAYOUT (portrait orientation, social media ready):
HEADER SECTION:
- League name: "${brandName}" in bold, premium typography
- Subtitle: "${subtitle}"
- Date: "Updated: ${today}"
- Small badminton/shuttlecock icon or logo

MAIN CONTENT - RANKINGS TABLE:
${playerList}

DESIGN DETAILS FOR RANKINGS:
- Top 3 players should have gold, silver, bronze accent colors/highlights
- Each row should be clearly readable with player name on left, points on right
- Use modern sans-serif typography
- Add subtle glow effects for top 3 positions
- Include small trophy/medal icons for positions 1-3

FOOTER:
- "🏸 One Shamelin Badminton Hall"
- "yuqiuren.lovable.app"

STYLE NOTES:
- Make it look like a premium sports infographic
- Include subtle particle effects or bokeh in background
- Use dramatic shadows and depth
- Typography should be bold and impactful
- Overall dimensions should be suitable for WhatsApp/social media sharing (portrait orientation, roughly 4:5 or 3:4 aspect ratio)`;

    console.log("Generating ranking image with AI...");

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image-preview",
        messages: [
          {
            role: "user",
            content: prompt,
          },
        ],
        modalities: ["image", "text"],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("AI gateway error:", response.status, errorText);
      
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limit exceeded. Please try again in a moment." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: "AI credits depleted. Please add funds to continue." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      
      throw new Error(`AI gateway returned ${response.status}: ${errorText}`);
    }

    const data = await response.json();
    console.log("AI response received");

    // Extract the generated image
    const imageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    
    if (!imageUrl) {
      console.error("No image in response:", JSON.stringify(data));
      throw new Error("No image generated by AI");
    }

    return new Response(
      JSON.stringify({ imageUrl }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Error generating ranking image:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Failed to generate image" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
